name: currency_exchange
services:
  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    env_file: currency_exchange/.env
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
  broker:
    image: rabbitmq:alpine
    ports:
      - 5672:5672
    env_file: currency_exchange/.env
    depends_on:
      - db
