# Generated by Django 4.2.6 on 2023-10-31 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Only insert values which correspond to symbols supported by yfinance', max_length=8, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=0, message="The currency's symbol can't be empty")])),
            ],
        ),
    ]
