# Generated by Django 4.2.6 on 2023-11-01 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency_exchange', '0002_init_currencies'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyExchangeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_rate', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='currency_exchange.currency')),
            ],
            options={
                'db_table': 'currency_exchange_info',
                'ordering': ['-created'],
            },
        ),
    ]
